# Lab 1: Introduction to Python

## 1. Basic calculations in Python

In [8]:
2+3

5

In [9]:
2/3

0.6666666666666666

In [10]:
3-5

-2

### Problem 1

In [11]:
15 + 27

42

In [12]:
3 * 2 -5

1

In [13]:
3*(2-5)

-9

In [14]:
12/0

ZeroDivisionError: division by zero

In [15]:
10**3

1000

In [16]:
10 * * 2

SyntaxError: invalid syntax (2137562372.py, line 1)

### Problem 2

In [17]:
course="PSTAT 5A"

In [18]:
cc='The course capacity for '

In [19]:
section_capacity = 25

In [20]:
number_sections = 10

In [21]:
course_capacity = section_capacity * number_sections

In [22]:
course_capacity

250

### Problem 3

In [23]:
# You can just type the variable name or use "print"!
cc

'The course capacity for '

In [24]:
print(number_sections)

10

### Problem 4

In [25]:
print(cc+course+': ' + str(course_capacity))
# addition works as concatenation inside print function

The course capacity for PSTAT 5A: 250

### Problem 5

In [26]:
print(Cc+course+': ' + str(course_capacity))

NameError: name 'Cc' is not defined

In [27]:
Print(cc+course+': ' + str(course_capacity))

NameError: name 'Print' is not defined

## 2. Useful shortcuts

### Esc + Y: Markdown to Python

### Esc + M: Python to Markdown

### Esc + A: Insert a cell above

### Esc + B: Insert a cell below

## 3. Module

In [28]:
# Method 1
import numpy
numpy.sqrt(2)

np.float64(1.4142135623730951)

In [29]:
# Method 2
from numpy import *
sqrt(2)

np.float64(1.4142135623730951)

In [30]:
# Method 3
import numpy as np
np.sqrt(2)

np.float64(1.4142135623730951)

In [31]:
# Method 4
from numpy import sqrt
sqrt(2)

np.float64(1.4142135623730951)

In [32]:
# In practice, you are not recommended to import the same module for more than once in a python file!

## 4. Tables

In [33]:
from datascience import *

In [34]:
IG=Table().with_columns("User", ["Katy", "Justin", "Taylor"],
"Followers (in millions)", [202, 293, 282])

In [35]:
IG

User   | Followers (in millions)
Katy   | 202
Justin | 293
Taylor | 282

### Problem 6

In [36]:
IG1 = Table().with_columns("User", ["Katy", "Justin", "Taylor"],
"Followers (in millions)", [202, 293, 282],
"Handle", ["Katyperry", "lilbieber", "taylorswift"])

In [37]:
IG1

User   | Followers (in millions) | Handle
Katy   | 202                     | Katyperry
Justin | 293                     | lilbieber
Taylor | 282                     | taylorswift

## 5. Comments

In [38]:
# This is a single-line comment
x = 5
print(x)

5

In [39]:
"""
This is a multi-line comment.
It can use multiple lines.
"""

x = 5
print(x)

5